"""create table cheikhs

Revision ID: 056e741690bc
Revises: c39de4361f33
Create Date: 2026-09-08 09:29:16.481824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056e741690bc'
down_revision: Union[str, Sequence[str], None] = 'c39de4361f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheikhs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('foyer', sa.Text(), nullable=True),
    sa.Column('dateCreation', sa.Date(), nullable=True),
    sa.Column('dateMaj', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheikhs_id'), 'cheikhs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheikhs_id'), table_name='cheikhs')
    op.drop_table('cheikhs')
    # ### end Alembic commands ###
