"""create media tables

Revision ID: 92b5d2f9da2b
Revises: a5767d51f6fe
Create Date: 2026-09-09 10:40:32.268171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b5d2f9da2b'
down_revision: Union[str, Sequence[str], None] = 'a5767d51f6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('chemin', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('taille', sa.Integer(), nullable=False),
    sa.Column('dateCreation', sa.Date(), nullable=False),
    sa.Column('dateMaj', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medias_id'), 'medias', ['id'], unique=False)
    op.create_table('media_asso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_asso_id'), 'media_asso', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_asso_id'), table_name='media_asso')
    op.drop_table('media_asso')
    op.drop_index(op.f('ix_medias_id'), table_name='medias')
    op.drop_table('medias')
    # ### end Alembic commands ###
