"""create table wadjous and link it to table cheikhs

Revision ID: 9bc35650e74a
Revises: b7cf31a1f303
Create Date: 2026-09-08 12:08:43.949635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc35650e74a'
down_revision: Union[str, Sequence[str], None] = 'b7cf31a1f303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wadjous',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=True),
    sa.Column('medialink', sa.Text(), nullable=True),
    sa.Column('dateCreation', sa.Date(), nullable=True),
    sa.Column('dateMaj', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wadjous_id'), 'wadjous', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wadjous_id'), table_name='wadjous')
    op.drop_table('wadjous')
    # ### end Alembic commands ###
