"""create table cheikhs

Revision ID: a5767d51f6fe
Revises: 9bc35650e74a
Create Date: 2026-09-08 14:16:01.978716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5767d51f6fe'
down_revision: Union[str, Sequence[str], None] = '9bc35650e74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wadjous', sa.Column('id_cheikh', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wadjous', 'cheikhs', ['id_cheikh'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wadjous', type_='foreignkey')
    op.drop_column('wadjous', 'id_cheikh')
    # ### end Alembic commands ###
