"""edit table article

Revision ID: c39de4361f33
Revises: 5997486ad130
Create Date: 2026-09-07 12:04:42.291985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39de4361f33'
down_revision: Union[str, Sequence[str], None] = '5997486ad130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
